name: 'generate-allure-report'
description: 'Generate Allure Report'
author: 'Andrey Sorokin'
branding:
  icon: 'bar-chart'
  color: 'yellow'
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  allure-results:
    description: 'Allure test result directory'
    required: true
    default: 'allure-results'
  report-name:
    description: 'The name to be shown on top of the Overview tab in the Allure report'
    required: false
    default: 'Allure Report'
  ci-name:
    description: 'The name of the CI server'
    required: false
    default: 'GitHub Action: {{ github.workflow }}'
  allure-report:
    description: 'Allure report directory'
    required: true
    default: 'allure-report'
  site-source:
    description: 'Directory where the website source files (e.g., from the gh-pages branch) are checked out'
    required: true
    default: 'site-source'
  allure-history:
    description: 'Allure report history base directory stored in the site source directory'
    required: true
    default: 'allure-history'
  site-path:
    description: 'Subdirectory within the site source directory where the Allure report will be published'
    required: false
    default: ''
  number-reports-to-keep:
    description: 'Number of previous Allure reports to keep. Set to 0 to keep all reports.'
    required: false
    default: 20
  site-url:
    description: 'Custom URL to use instead of the default GitHub Pages URL for the Allure report'
    required: false
    default: ''
