name: 'generate-allure-report'
description: 'Generate Allure Report'
author: 'Andrey Sorokin'
branding:
  icon: 'bar-chart'
  color: 'yellow'
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  allure-results:
    description: 'Allure test result directory created by tests.'
    required: true
    default: 'allure-results'
  website:
    description: 'Website directory (e.g., checkouted from the gh-pages branch).'
    required: true
    default: 'gh-pages-dir'
  reports-site-path:
    description: 'Allure report path within the website.'
    required: false
    default: 'builds/tests'
  reports-site:
    description: 'Allure reports directory, to be pushed to the website repository at the `reports-site-path`. Each report on the subfolder with the github run number. If specified the old reports copied from `website`. By default create report inplace in `website`/`reports-site-path`.'
    required: true
    default: ''
  website-url:
    description: 'Custom URL to use instead of the default GitHub Pages URL for the website where Allure report will be published'
    required: false
    default: ''
  report-name:
    description: 'The name to be shown on top of the Overview tab in the Allure report'
    required: false
    default: 'Allure Test Report'
  ci-name:
    description: 'The name of the CI server'
    required: false
    default: 'GitHub Action: {{ vars.github_workflow }}'
  max-reports:
    description: 'Number of previous Allure reports to keep. Set to 0 to keep all reports.'
    required: false
    default: 20
  summary:
    description: 'Summary text for the action to be shown in the GitHub Actions UI. Set to empty string to disable.'
    required: false
    default: '\n## Test report\n[Allure test report]({{ outputs["REPORT_URL"] }})\n\n'
outputs:
  report-url:
    description: 'URL to the Allure report'
  reports-site-path:
    description: 'Copy of input reports-site-path'
  reports-site:
    description: 'Folder where the reports located. To be published in `reports-site-path` in your website'
  reports-root-url:
    description: 'Root of all reports with index.html that auto-redirect to the last report'
