name: 'generate-allure-report'
description: 'Generate Allure Report'
author: 'Andrey Sorokin'
branding:
  icon: 'bar-chart'
  color: 'yellow'
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  allure-results:
    description: 'Allure test result directory created by tests.'
    required: true
    default: 'allure-results'
  website-source:
    description: 'Website checkout location (e.g., from the gh-pages branch).'
    required: true
    default: 'gh-pages'
  report-path:
    description: 'Allure report path within the website.'
    required: false
    default: ''
  allure-report:
    description: 'Generated Allure report directory, to be pushed to the website repository at the `report-path`.'
    required: true
    default: 'allure-report'
  website-url:
    description: 'Custom URL to use instead of the default GitHub Pages URL for the website where Allure report will be published'
    required: false
    default: ''
  report-name:
    description: 'The name to be shown on top of the Overview tab in the Allure report'
    required: false
    default: 'Allure Test Report'
  ci-name:
    description: 'The name of the CI server'
    required: false
    default: 'GitHub Action: {{ github.workflow }}'
  max-history-reports:
    description: 'Number of previous Allure reports to keep. Set to 0 to keep all reports.'
    required: false
    default: 20
